version: '3'

services:
  nodejs:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./.env:/usr/src/app/.env


  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: