
name: DEV build

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # - name: configure ssh key
    #   env:
    #     SSH_KEY: ${{ secrets.SSH_PRIV_KEY }}
    #     host: ${{ secrets.SERVER_IP }}
    #     port: ${{ secrets.SERVER_PORT }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     password: ${{ secrets.SSH_PASSWORD }}
    #     appPath: ${{ secrets.PATH_TO_APP_DEV }}
    #   run: echo $SSH_KEY > id_rsa && chmod 600 id_rsa | echo $host
    # - name: Deploy to server first method
    #   run: |
    #     ssh ubuntu@51.91.58.190 -p 2222 -o StrictHostKeyChecking=no <<EOF
    #     cd $appPath
    #     git pull
    #     docker-compose down
    #     docker-compose up -d
    #     exit
    #     EOF

    # - name: Build Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: false
    #     tags: ${{ secrets.DOCKER_USERNAME }}/BLOG:develop
    #     build-args: |
    #       NODE_ENV=$DEV_ENV
    #       PORT=$DEV_PORT

    - name: Deploy to server second method
      uses: appleboy/ssh-action@master
      env:
        appPath: ${{ secrets.PATH_TO_APP_DEV }}

      with:
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        envs: appPath
        script: |
          cd $appPath
          docker ps
          echo $(pwd) and $appPath and $host > /root/log.log 
# cd $appPath
#           pwd
#           git pull
#           docker ps
#           docker compose down
#           docker compose up -d          