

name: MASTER build

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      env:
        SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        appPath: ${{ secrets.PATH_TO_APP_PROD }}
      run: echo $SSH_KEY > id_rsa && chmod 600 id_rsa
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no $username@$host <<EOF
        cd $appPath
        git pull
        docker-compose down
        docker-compose up -d
        exit
        EOF

    # - name: Build Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: false
    #     tags: ${{ secrets.DOCKER_USERNAME }}/BLOG:develop
    #     build-args: |
    #       NODE_ENV=$PROD_ENV
    #       PORT=$PROD_PORT

    # - name: Deploy to server
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SERVER_IP }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     password: ${{ secrets.SSH_PASSWORD }}
    #     script: |
    #       docker-compose down
    #       docker-compose up -d
